---
- name: Install OpenVPN in tap mode
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Install packages
      apt:
        name:
          - openvpn
          - iperf3
          - easy-rsa
        state: present
        update_cache: true

    - name: copy OpenVPN config file
      template:
        src: server-tap.conf.j2
        dest: /etc/openvpn/server.conf
        owner: root
        group: root
        mode: 0644

    - name: copy key file
      template:
        src: static.key
        dest: /etc/openvpn/static.key
        owner: root
        group: root
        mode: 0644

    - name: Create systemd unit
      template:
        src: openvpn.service
        dest: /etc/systemd/system/openvpn@.service
        owner: root
        group: root
        mode: 0644

    - name: Start OpenVPN
      systemd:
        name: openvpn@server
        state: restarted
        enabled: true
        daemon_reload: true
